
title: وبلاگ فارسی من
description:  

author: Amir Pourmand
email: pourmand1376@gmail.com

timezone: +03:30

url: http://pourmand1376.github.io
root: /blog-fa
static: /static
imageurl: /static/images

default_floor: blog

disqus_shortname: pourmand
google_analytics: 

github_repo: https://github.com/pourmand1376/blog-fa/blob/master/

twitter: http://twitter.com/AmirPourmand76
github: http://github.com/pourmand1376
